### ISSUE TITLE
분류 오류에 대한 질문.

### ISSUE THREAD

**Issue by esgyu** [ai4r/lip_reading_21words#2]
처음 환경 구축 이후 demo_main.py 실행시에는 정상적으로 동작함을 확인했는데, 이후 재 실행 시 마지막 단어를 제외하고 모두
'가져와' 로 분류하는 상황이 발생합니다.  
구현 환경은 python=3.5.4, dlib=19.10를 사용한 것 이외에는 requirements.txt와 동일하게 구성되어있습니다.
혹시 수정해봐야 하는 부분이 있을까요?  
![Screenshot from 2020-07-09 09-59-03](https://user-images.githubusercontent.com/24788424/86985614-9d9ca780-c1cc-11ea-8189-9bd6974a64aa.png)

**Comment by opo6954** [comment]
1. 같은 소스를 그대로 실행하고 바로 재실행했을 때의 결과가 다른건가요?

2. 만일 재실행할 때 test_batch.bin 파일을 제거한 후에 실행해보시겠어요?

**Comment by esgyu** [comment]
1. 정상작동 확인 후 몇시간 뒤에 재실행해 보았습니다.

2. test_batch.bin 제거 후 실행해도 동일하게 '가져와'로만 분류합니다.  

내부 코드를 수정하거나 환경이 바뀐적은 없고 다른 동영상에 대해서 코드를 실행했던 적이 있는데, 영향을 끼칠 수 있나요?

**Comment by opo6954** [comment]
코드상의 오류는 없는 것 같고 다른 동영상을 대상으로 실행 했을 때의 인식결과가 "가져와"로만 인식하는 것 같고 이는 동영상 자체의 문제일 수도 있습니다.

혹시 다른 동영상으로 확인해보시겠나요?

만일 그래도 계속 인식결과가 같으면 제가 다시 한번 자세하게 보겠습니다.

**Comment by opo6954** [comment]
아 그리고 실행 후의 첫화면도 보내주시겠어요?
여러 숫자가 나오는 화면이요

**Comment by esgyu** [comment]
tensorflow, tensorflow-gpu버전을 1.15.2에서 1.12.0으로 다운그레이드하여 실행해보았더니 다시 정상 작동하는 것 같습니다.

**Comment by opo6954** [comment]
본래 개발 버전이 1.12인데 자동으로 버전을 맞춰주는 봇때문에 1.15로 requirements에 적었었습니다

다시금 1.12에서만 동작한다고 수정해놓겠습니다
