### ISSUE TITLE
모델 성능 관련 질문

### ISSUE THREAD

**Issue by esgyu** [ai4r/lip_reading_21words#4]
안녕하세요.  
해당 repo를 사용하다가 궁금한 점이 있어 질문을 드립니다.  

demo video을 통한 결과에서 총 21번의 발화에 대해 15개만 맞게 분류하는 모습을 확인했는데, 혹시 해당 모델의 각 클래스별 정확도 같은 성능 지표를 알 수 있는 방법이 있을까요?

**Comment by opo6954** [comment]
성능지표 관련 코드를 올렸습니다.
eval_demo.py를 실행하면 됩니다.

단 weight 파일의 경우 기존의 demo_main.py와 eval_demo.py가 공유하지 않으므로(제가 개발을 하지 않아서 자세히는 모르겠으나 아마 텐서플로우 버전 문제로 생각됩니다.) weight 파일을 따로 받으시고 테스트 파일의 경우 마찬가지로 따로 다운로드를 받으셔서 테스트하시면 됩니다.

일단 제가 올린 코드는 "입술 주변이 오려진" 동영상입니다. 만일 일반 동영상에서의 테스트 지표를 원하시면 demo_main.py와 eval_demo.py 소스 코드를 합쳐서 새롭게 개발해야 합니다. 저도 코드를 이어받은 입장이라 계속 찾아보고는 있는데 관련된 것이 있으면 다시금 올려드리겠습니다.

**Comment by isangu** [comment]
혹시 해당 모델을 학습할 때 사용한 데이터 셋을 받을 수 있을까요?

**Comment by opo6954** [comment]
데이터셋을 받을 수 있는 주소를 개인 메일로 보내 드리겠습니다. 공개된 데이터가 아니므로 본인만 사용하셔야 합니다.

**Comment by isangu** [comment]
lsgyu@etri.re.kr로 보내주시면 감사하겠습니다.

**Comment by opo6954** [comment]
메일로 보내드렸습니다.
